/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClausesRouteImport } from './routes/clauses'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DraftingRouteImport } from './routes/drafting'
import { Route as HoldsRouteImport } from './routes/holds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as MattersMatterIdRouteImport } from './routes/matters.$matterId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClausesRoute = ClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftingRoute = DraftingRouteImport.update({
  id: '/drafting',
  path: '/drafting',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldsRoute = HoldsRouteImport.update({
  id: '/holds',
  path: '/holds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/$contractId',
  path: '/$contractId',
  getParentRoute: () => ContractsRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => DocumentsRoute,
} as any)
const MattersMatterIdRoute = MattersMatterIdRouteImport.update({
  id: '/$matterId',
  path: '/$matterId',
  getParentRoute: () => MattersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/clauses': typeof ClausesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/drafting': typeof DraftingRoute
  '/holds': typeof HoldsRoute
  '/login': typeof LoginRoute
  '/matters': typeof MattersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/clauses': typeof ClausesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/drafting': typeof DraftingRoute
  '/holds': typeof HoldsRoute
  '/login': typeof LoginRoute
  '/matters': typeof MattersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/clauses': typeof ClausesRoute
  '/clients': typeof ClientsRouteWithChildren
  '/contracts': typeof ContractsRouteWithChildren
  '/documents': typeof DocumentsRouteWithChildren
  '/drafting': typeof DraftingRoute
  '/holds': typeof HoldsRoute
  '/login': typeof LoginRoute
  '/matters': typeof MattersRouteWithChildren
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approvals'
    | '/audit'
    | '/calendar'
    | '/clauses'
    | '/clients'
    | '/contracts'
    | '/documents'
    | '/drafting'
    | '/holds'
    | '/login'
    | '/matters'
    | '/reports'
    | '/search'
    | '/tasks'
    | '/templates'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/documents/$documentId'
    | '/matters/$matterId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approvals'
    | '/audit'
    | '/calendar'
    | '/clauses'
    | '/clients'
    | '/contracts'
    | '/documents'
    | '/drafting'
    | '/holds'
    | '/login'
    | '/matters'
    | '/reports'
    | '/search'
    | '/tasks'
    | '/templates'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/documents/$documentId'
    | '/matters/$matterId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approvals'
    | '/audit'
    | '/calendar'
    | '/clauses'
    | '/clients'
    | '/contracts'
    | '/documents'
    | '/drafting'
    | '/holds'
    | '/login'
    | '/matters'
    | '/reports'
    | '/search'
    | '/tasks'
    | '/templates'
    | '/clients/$clientId'
    | '/contracts/$contractId'
    | '/documents/$documentId'
    | '/matters/$matterId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  CalendarRoute: typeof CalendarRoute
  ClausesRoute: typeof ClausesRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ContractsRoute: typeof ContractsRouteWithChildren
  DocumentsRoute: typeof DocumentsRouteWithChildren
  DraftingRoute: typeof DraftingRoute
  HoldsRoute: typeof HoldsRoute
  LoginRoute: typeof LoginRoute
  MattersRoute: typeof MattersRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  TasksRoute: typeof TasksRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clauses': {
      id: '/clauses'
      path: '/clauses'
      fullPath: '/clauses'
      preLoaderRoute: typeof ClausesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafting': {
      id: '/drafting'
      path: '/drafting'
      fullPath: '/drafting'
      preLoaderRoute: typeof DraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holds': {
      id: '/holds'
      path: '/holds'
      fullPath: '/holds'
      preLoaderRoute: typeof HoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof ContractsRoute
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/matters/$matterId': {
      id: '/matters/$matterId'
      path: '/$matterId'
      fullPath: '/matters/$matterId'
      preLoaderRoute: typeof MattersMatterIdRouteImport
      parentRoute: typeof MattersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ContractsRouteChildren {
  ContractsContractIdRoute: typeof ContractsContractIdRoute
}

const ContractsRouteChildren: ContractsRouteChildren = {
  ContractsContractIdRoute: ContractsContractIdRoute,
}

const ContractsRouteWithChildren = ContractsRoute._addFileChildren(
  ContractsRouteChildren,
)

interface DocumentsRouteChildren {
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface MattersRouteChildren {
  MattersMatterIdRoute: typeof MattersMatterIdRoute
}

const MattersRouteChildren: MattersRouteChildren = {
  MattersMatterIdRoute: MattersMatterIdRoute,
}

const MattersRouteWithChildren =
  MattersRoute._addFileChildren(MattersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  CalendarRoute: CalendarRoute,
  ClausesRoute: ClausesRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ContractsRoute: ContractsRouteWithChildren,
  DocumentsRoute: DocumentsRouteWithChildren,
  DraftingRoute: DraftingRoute,
  HoldsRoute: HoldsRoute,
  LoginRoute: LoginRoute,
  MattersRoute: MattersRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  TasksRoute: TasksRoute,
  TemplatesRoute: TemplatesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
